;SETTINGS -----------------------------------------------------------------
#Requires AutoHotkey v2.0
#SingleInstance Force
Version := "1.3"
CoordMode "Mouse", "Screen"
CoordMode "Pixel", "Screen"
DllCall("SetThreadDpiAwarenessContext", "ptr", -4, "ptr")

;VARIABLES -----------------------------------------------------------------
StartTime := A_TickCount
TimeElapsed := 0
Counter := 0

UIDisplay := ''
boxes := []
home := box()
bell := box()
settingsStr := '11111111111111110'
settingsStrLen := 18
invStr := '0,0,0,0'
colorTolerance := 6
KeepAnthony := KeepButter := KeepCentury := KeepChicken := KeepClever := KeepCourt := KeepCrown := KeepDrake := KeepGift := KeepKitchen := KeepMinion := KeepNoble := KeepPantry := KeepRed := KeepWhite := TakeScreenshots := WaitForDespawn := DoShortWaits := 1

;BOX CLASS -----------------------------------------------------------------
class Box{
    __New(x1:=0, y1:=0, x2:=0, y2:=0)
    {
        this.x1 := x1
        this.y1 := y1
        this.x2 := x2
        this.y2 := y2
		this.ticked := false
		if (this.x1 = this.x2){
			this.real := false
		}
		else{
			this.real := true
		}
    }
}
;FUNCTIONS -----------------------------------------------------------------
;PARSE INVENTORY BOXES FUNCTION
ParseInventory(firstx,firsty,secondx,secondy){
	global boxes,invStr,invList
	boxWidth := (secondx-firstx)/5
	boxHeight := (secondy-firsty)/4
	boxes := []
	if(firstx>=secondx || firsty>=secondy){
		MsgBox("Invalid inventory coords! Try again.","Zoopa's Deli Macro V" Version)
		return false
	}
	invStr := firstx ',' firsty ',' secondx ',' secondy
	invList := [firstx,firsty,secondx,secondy]
	Loop 4{
		rIndex := A_Index-1
		Loop 5{
			cIndex := A_Index-1
			boxes.Push(box(firstx+boxWidth*cIndex,firsty+boxHeight*rIndex,firstx+boxWidth*cIndex+boxWidth,firsty+boxHeight*rIndex+boxHeight))
		}
	}
	return true
}
;READ SETTINGS FUNCTION
ReadSettings(){
	global settingsStr,home,bell,invList, KeepAnthony,KeepButter,KeepCentury,KeepChicken,KeepClever,KeepCourt,KeepCrown,KeepDrake,KeepGift,KeepKitchen,KeepMinion,KeepNoble,KeepPantry,KeepRed,KeepWhite,TakeScreenshots,WaitForDespawn,DoShortWaits
	settingsFile := A_ScriptDir "\ZDMsettings.txt"
	if (FileExist(settingsFile)){
		fileList := StrSplit(FileRead(settingsFile), "`n", "`r")
		if (StrLen(fileList[2])=settingsStrLen){
			settingsStr := fileList[2]
		}
		invList := StrSplit(fileList[3],",", "`r")
		if (invList.Length=4){
			ParseInventory(invList[1],invList[2],invList[3],invList[4])
		}
		homeList := StrSplit(fileList[4],",", "`r")
		if(homeList.Length=4){
			home := box(homeList[1],homeList[2],homeList[3],homeList[4])
		}
		bellList := StrSplit(fileList[5],",", "`r")
		if (bellList.Length=4){
			bell := box(bellList[1],bellList[2],bellList[3],bellList[4])
		}
	}

	KeepAnthony := (SubStr(settingsStr,1,1) = "1")
	KeepButter := (SubStr(settingsStr,2,1) = "1")
	KeepCentury := (SubStr(settingsStr,3,1) = "1")
	KeepChicken := (SubStr(settingsStr,4,1) = "1")
	KeepClever := (SubStr(settingsStr,5,1) = "1")
	KeepCourt := (SubStr(settingsStr,6,1) = "1")
	KeepCrown := (SubStr(settingsStr,7,1) = "1")
	KeepDrake := (SubStr(settingsStr,8,1) = "1")
	KeepGift := (SubStr(settingsStr,9,1) = "1")
	KeepKitchen := (SubStr(settingsStr,10,1) = "1")
	KeepMinion := (SubStr(settingsStr,11,1) = "1")
	KeepNoble := (SubStr(settingsStr,12,1) = "1")
	KeepPantry := (SubStr(settingsStr,13,1) = "1")
	KeepRed := (SubStr(settingsStr,14,1) = "1")
	KeepWhite := (SubStr(settingsStr,15,1) = "1")
	TakeScreenshots := (SubStr(settingsStr,16,1) = "1")
	WaitForDespawn := (SubStr(settingsStr,17,1) = "1")
	DoShortWaits := (SubStr(settingsStr,18,1) = "1")
}
;WRITE SETTINGS FUNCTION
WriteSettings(){
	global settingsStr,invStr,home,bell
	settingsFile := A_ScriptDir "\ZDMsettings.txt"
	if (FileExist(settingsFile)){
		FileDelete(settingsFile)
	}
	FileAppend("SETTING STRING | INV | HOME | BELL`n", settingsFile)
	FileAppend(settingsStr "`n", settingsFile)
	FileAppend(invStr '`n', settingsFile)
	FileAppend(home.x1 ',' home.y1 ',' home.x2 ',' home.y2 '`n', settingsFile)
	FileAppend(bell.x1 ',' bell.y1 ',' bell.x2 ',' bell.y2 '`n', settingsFile)
	FileAppend("DO NOT EDIT THIS FILE!", settingsFile)
}
;NATURAL MOUSE MOVEMENT FUNCTION
MouseNatural(){
	MouseMove 1, 2, 100, "R"
	MouseMove -2, -1, 100, "R"
	MouseMove 1, -1, 100, "R"
	MouseMove 1, -1, 100, "R"
	MouseMove -1, 1, 100, "R"
}
;DROP ITEM FUNCTION
DropItem(X1, Y1){
	MouseMove X1, Y1
	MouseNatural()
	Sleep 20
	MouseNatural()
	Sleep 20
	Click
	MouseNatural()
	Click
	Sleep 20
	MouseClick "right"
	Sleep 20
	MouseMove 25, 15, 100, "R"
	Sleep 20
	MouseNatural()
	Sleep 20
	MouseClick "left"
}
;IS THE INVENTORY OPEN CHECK FUNCTION
IsInvOpen(){
if (ColorListSearch(home.x1,home.y1,home.x2,home.y2,[0x8D807A],1)||ColorListSearch(home.x1,home.y1,home.x2,home.y2,[0x94C19B],1)){
	return true
}
else{
	return false
}
}
;PIXEL SEARCH LIST FUNCTION
ColorListSearch(X1,Y1,X2,Y2,ColorList,tolerance := colorTolerance){ ;Only returns true if all colors exist in the specific region
	for color in ColorList{
		if (PixelSearch(&Px, &Py, X1, Y1, X2, Y2, color, tolerance)){
			continue
		}
		else{
			return false
		}
	}
	return true
}
;ITEM SEARCH FUNCTION
ItemSearch(MX1, MY1, MX2, MY2, debugMode := false){
	global KeepDrake, KeepAnthony, KeepMinion, KeepCentury, KeepChicken, KeepClever, KeepCourt, KeepCrown, KeepPantry, KeepGift, KeepWhite, KeepButter, KeepRed, KeepNoble
	str := ''
	if (ColorListSearch(MX1,MY1,MX2,MY2,[0xD3AB31,0xD4F2D4,0xFEFFFE,0x7DB4E3],8)){
		if (debugMode){
			str .= 'Candy Crumbs | '
		}
		else{
			return false
		}
	}
	if (ColorListSearch(MX1,MY1,MX2,MY2,[0x54AD4D,0x899310,0xA5AE4B])){
		if (debugMode){
			str .= 'Greater Dungeon Candy | '
		}
		else{
			return false
		}
	}
	if (ColorListSearch(MX1,MY1,MX2,MY2,[0xFDFEFE,0x355CB4,0x328CF9])){
		if (debugMode){
			str .= 'Lesser Dungeon Candy | '
		}
		else{
			return false
		}
	}
	if (ColorListSearch(MX1,MY1,MX2,MY2,[0xA657C2,0x6A4C24,0xF0F0DE,0x532A41])){
		if (debugMode){
			str .= 'Rich Man Delight | '
		}
		else{
			return false
		}
	}
	if ((KeepAnthony || debugMode) && ColorListSearch(MX1,MY1,MX2,MY2,[0xFFFFFF,0x3F3E52,0x443E50],4) && !(ColorListSearch(MX1,MY1,MX2,MY2,[0x4E7569,0x3D4E86],4)) && !(ColorListSearch(MX1, MY1, MX2, MY2, [0xFFFFFF,0x252945,0x75A095], 4))){
		if (debugMode){
			str .= 'Tall Anthony | '
		}
		else{
			return 'Tall Anthony'
		}
	}
	if ((KeepButter || debugMode) && ColorListSearch(MX1,MY1,MX2,MY2,[0xA157C2,0xB6E5A3,0xC69936])){
		if (debugMode){
			str .= 'Buttered Greens | '
		}
		else{
			return 'Buttered Greens'
		}
	}
	if ((KeepCentury || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0x595E31,0x99A83B,0x182120])){
		if (debugMode){
			str .= 'Century Cube | '
		}
		else{
			return 'Century Cube'
		}
	}
	if ((KeepChicken || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xAD3F3F,0xFDFDFD,0xCAAC92])){
		if (debugMode){
			str .= 'Big Chicken | '
		}
		else{
			return 'Big Chicken'
		}
	}
	if ((KeepClever || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xA057BF,0xFFBEFF,0x1D1D2A])){
		if (debugMode){
			str .= 'Clever Cube | '
		}
		else{
			return 'Clever Cube'
		}
	}
	if ((KeepCourt || debugMode) && (ColorListSearch(MX1, MY1, MX2, MY2, [0xFFFFFD,0x2B2A3A,0x42665A,0x3E4E86]) || ColorListSearch(MX1, MY1, MX2, MY2, [0xFFFFFD,0x477067,0x38487C]))){
		if (debugMode){
			str .= 'Court Jester Set | '
		}
		else{
			return 'Court Jester Set'
		}
	}
	if ((KeepCrown || debugMode) && (ColorListSearch(MX1, MY1, MX2, MY2, [0xA8B268,0xA157C0], 3) && !(ColorListSearch(MX1, MY1, MX2, MY2, [0xB4E3AB], 3)))){
		if (debugMode){
			str .= 'Crown | '
		}
		else{
			return 'Crown'
		}
	}
	if ((KeepDrake || debugMode) && (ColorListSearch(MX1, MY1, MX2, MY2, [0xA157C0,0x95363C, 0x676655], 7) || ColorListSearch(MX1, MY1, MX2, MY2, [0xA76CC1,0x6F282B]))){
		if (debugMode){
			str .= 'Drake Set | '
		}
		else{
			return 'Drake Set'
		}
	}
	if ((KeepGift || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xEDF0EF,0x95C192,0x4076AF,0xBC6E7D])){
		if (debugMode){
			str .= 'Gift Fruit | '
		}
		else{
			return 'Gift Fruit'
		}
	}
	if ((KeepKitchen || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0x1E2C30,0x192327], 4)){
		if (debugMode){
			str .= 'Kitchen Cube | '
		}
		else{
			return 'Kitchen Cube'
		}
	}
	if ((KeepMinion || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xB13D3B,0x477661,0x595650],8)){
		if (debugMode){
			str .= 'Minion | '
		}
		else{
			return 'Minion'
		}
	}
	if ((KeepNoble || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0x9B53BB,0x528FD7,0x82B279])){
		if (debugMode){
			str .= 'Noble Blue Seed | '
		}
		else{
			return 'Noble Blue Seed'
		}
	}
	if ((KeepPantry || debugMode) && (ColorListSearch(MX1, MY1, MX2, MY2, [0xFFFFFF,0x252945,0x75A095])) && !(ColorListSearch(MX1, MY1, MX2, MY2, [0x3D4E86],4))){
		if (debugMode){
			str .= 'Pantry Leech Head | '
		}
		else{
			return 'Pantry Leech Head'
		}
	}
	if ((KeepRed || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xE9592F,0xA463C0])){
		if (debugMode){
			str .= 'Red Bean | '
		}
		else{
			return 'Read Bean'
		}
	}
	if ((KeepWhite || debugMode) && ColorListSearch(MX1, MY1, MX2, MY2, [0xD4D2C8,0xE0E670,0xE7E6D8])){
		if (debugMode){
			str .= 'White Salamander Egg | '
		}
		else{
			return 'White Salamander Egg'
		}
	}
	if (debugMode){
		return str
	}
	else {
		return false
	}
}
;DRAWBOX FUNCTION
DrawBox(gui, x1, y1, x2, y2, label:="") {
    thickness := 2
    color := "FF0000"
    gui.Add("Text", "x" x1 " y" y1 " w" (x2-x1) " h" thickness " Background" color) ;top
    gui.Add("Text", "x" x1 " y" (y2-thickness) " w" (x2-x1) " h" thickness " Background" color) ;bottom
    gui.Add("Text", "x" x1 " y" y1 " w" thickness " h" (y2-y1) " Background" color) ;left
    gui.Add("Text", "x" (x2-thickness) " y" y1 " w" thickness " h" (y2-y1) " Background" color) ;right
	gui.Add("Text", "x" x1+5 " y" y1+5 " cWhite BackgroundTrans", label)
}

;END FUNCTION DECLARATIONS

;BEGIN PROGRAM
ReadSettings()
MsgBox("Zoopa's Deli Macro V" Version " loaded. `nPress CTRL + I for controls and insutrctions. `nPress F7 to terminate.","Zoopa's Deli Macro V" Version)
if (!home.real){
	MsgBox("Warning: Your settings are not properly setup. Please use CTRL + U to intiailize all of your coordinates.","Zoopa's Deli Macro V" Version)
}
;HOTKEYS ------------------------------------------------------------------
;TERMINATE HOTKEY F7
F7::{
ExitApp
Return
}
;RELOAD HOTKEY F6
F6::Reload 
;PAUSE HOTKEY PAUSEBREAK
\::Pause -1
;COUNTER FUNCTION
^k::{
	global Counter, StartTime, TimeElapsed
	TimeElapsed := A_TickCount - StartTime
	MsgBox("Waits Finished: " Counter "`nTime Elapsed:`nSeconds: " Round(TimeElapsed/1000, 1) "`nMinutes: " Round(TimeElapsed/60000, 1) "`nHours: " Round(TimeElapsed/3600000, 1) "`n`nWaits Per Hour: " Round(Counter/(TimeElapsed/3600000), 1),"Zoopa's Deli Macro V" Version)
	}
;WEBHOOK TEST
^;::{
	MsgBox("Webhook features not added yet","Zoopa's Deli Macro V" Version)
}
;SCREENSHOT MODE HOTKEY CTRL PERIOD
^.::{
	global TakeScreenshots
	if (TakeScreenshots = true){
	TakeScreenshots := false
	}
	else{
	TakeScreenshots := true
	}
	MsgBox("Take Screenshots: " TakeScreenshots,"Zoopa's Deli Macro V" Version)
	}
;INFO HOTKEY CTRL I
^i::{
	MsgBox("Zoopa's Deli Macro V" Version
	"`n`nCTRL + B to start`nCTRL + I for info`nCTRL + O for setting explanations`nCTRL + U to setup coordinates`nCTRL + J to draw coordinates`nCTRL + P to change settings`nCTRL + K to display Time Elapsed and Counter`nCTRL + PERIOD (.) to toggle Screenshot Mode`nCTRL + SEMICOLON (;) to test webhook`nBACKSLASH (\) to pause script`nF6 to reload script`nF7 to terminate script"
	"`n`n1 = True, 0 = False"
	"`nKeep Tall Anthony: " KeepAnthony
	"`nKeep Buttered Greens: " KeepButter 	
	"`nKeep Century Cube: " KeepCentury	
	"`nKeep Big Chicken: " KeepChicken
	"`nKeep Clever Cube: " KeepClever
	"`nKeep Court Jester Set: " KeepCourt	
	"`nKeep Crown: " KeepCrown
	"`nKeep Drake Set: " KeepDrake
	"`nKeep Gift Fruit: " KeepGift
	"`nKeep Kitchen Cube: " KeepKitchen
	"`nKeep Minion: " KeepMinion
	"`nKeep Noble Blue Seed: " KeepNoble 	
	"`nKeep Pantry Leech Head: " KeepPantry
	"`nKeep Red Bean: " KeepRed 
	"`nKeep White Salamander: " KeepWhite 
	"`nTake Screenshots: " TakeScreenshots
	"`nWait for Item Despawn: " WaitForDespawn
	"`nDo Short Waits: " DoShortWaits
	,"Zoopa's Deli Macro V" Version)
}
;EXPANDED INFO
^o::{
	MsgBox("If set to true:`nTakeScreenshots will take a picture of your inventory after each item you get but before dropping. Useful for debugging when the script improperly drops items.`nWaitForDespawn will wait a little more than a minute after you finish dropping items from your inventory between waits, this stops the dropped item hitbox from interfering with trying to access the booth. Can be avoided if your character is placed correctly.`nDoShortWaits will make you press 1 instead of 2, allowing you to macro short waits instead of long waits. Long waits are the default and are recommended.`nAll of the 'Keep X' Variables will keep that item if you get it from a wait, but if set to false you will drop that item if you get it from a wait.`n`nOther Features:`nThe counter hotkey CTRL + K will tell you how long the macro has been running as well as how many waits you have completed.`nThe draw boxes hotkey CTRL + J will draw visual indicators on your screen to show you where it is scanning for items and where you have your home button and bell button set. Useful for debugging and checking after you setup coordinates, but not necessary.`nThe screenshot mode toggle hotkey CTRL + PERIOD (.) simply flips the TakeScreenshots variable to the opposite of what it is currently.","Zoopa's Deli Macro V" Version)
}
;COORDS SETUP PROCESS
^u::{
	global home,bell
	MsgBox("This is the setup process for your inventory coordinates and necessary buttons. Please follow all of the steps carefully and make sure that your game window is set to the same size during setup as it will be during execution. Fullscreen or not will affect it as well.`n`nYou MUST dismiss or click OK on the text boxes before you press F8.","Zoopa's Deli Macro V" Version)
	
	MsgBox("First, open your inventory. Now hover your cursor over the top left corner of the very first slot in your inventory and press F8 after closing this text box.","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	firstx := x
	firsty := y

	MsgBox("Now hover your cursor over the bottom right corner of the very last slot in your inventory and press F8 after closing this text box.","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	secondx := x
	secondy := y
	if(!ParseInventory(firstx,firsty,secondx,secondy)){
		return
	}

	MsgBox("Now locate the home button. Hover your mouse cursor over the center of the home button and press F8 after closing this text box.","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	home := box(x-25,y-25,x+25,y+25)

	MsgBox("Now sit in the deli booth, go through the dialogue, hover your cursor over the center of the 'Ring Bell' popup and press F8 after closing this text box.","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	bell := box(x-50,y-25,x+50,y+25)
	WriteSettings()
	MsgBox("All set! You can check your coordinates with CTRL + J, the draw function.","Zoopa's Deli Macro V" Version)
}
;DRAW COORDINATES HOTKEY CTRL J
^j::{
    global boxes, UIDisplay
    if (IsObject(UIDisplay)) {
    	UIDisplay.Destroy()
		UIDisplay := ""
		return
	}
    UIDisplay := Gui("-DPIScale +AlwaysOnTop -Caption +ToolWindow +E0x20")
    UIDisplay.BackColor := "000000"
    UIDisplay.Show("x0 y0 w" A_ScreenWidth " h" A_ScreenHeight " NA")
    WinSetTransColor "000000", UIDisplay.Hwnd
    i := 1
	for box in boxes {
        DrawBox(UIDisplay, box.x1, box.y1, box.x2, box.y2, i)
		i++
    }
	DrawBox(UIDisplay,home.x1,home.y1,home.x2,home.y2,"Home")
	DrawBox(UIDisplay,bell.x1,bell.y1,bell.x2,bell.y2,"Ring Bell")
	return
}
;PREFERENCES CHANGE HOTKEY CTRL P
^p::{
	inputSettings := InputBox("Enter a string of 1s and 0s, where 1 represents True and 0 represents False. Each digit corresponds to the variable at the same place in the list below, where 'Keep Tall Anthony' is the first, and the 'DoShortWaits' setting is the last. Your string MUST be " settingsStrLen " characters long and should have NO spaces or other seperating characters.`nExample of a valid string:`n10001111001010110`n`nLIST:Tall Anthony, Buttered Greens, Century Cube, Big Chicken, Clever Cube, Court Jester, Crown, Drake Set, Gift Fruit, Kitchen Cube, Minion, Noble Blue Seeds, Pantry Leech Set, Red Bean, White Salamander, Take Screenshots, Wait For Despawn, Do Short Waits`n`nNote: You can verify your settings by pressing CTRL + I after you have finished.", "Zoopa's Deli Macro V" Version, "w600 h300")
	if (inputSettings.result != 'OK' || inputSettings.value = ''){
		return
	}
	newKeepString := inputSettings.value
	if (StrLen(newKeepString) = settingsStrLen){
		global settingsStr := newKeepString
		global KeepAnthony := (SubStr(settingsStr,1,1) = "1")
		global KeepButter := (SubStr(settingsStr,2,1) = "1")
		global KeepCentury := (SubStr(settingsStr,3,1) = "1")
		global KeepChicken := (SubStr(settingsStr,4,1) = "1")
		global KeepClever := (SubStr(settingsStr,5,1) = "1")
		global KeepCourt := (SubStr(settingsStr,6,1) = "1")
		global KeepCrown := (SubStr(settingsStr,7,1) = "1")
		global KeepDrake := (SubStr(settingsStr,8,1) = "1")
		global KeepGift := (SubStr(settingsStr,9,1) = "1")
		global KeepKitchen := (SubStr(settingsStr,10,1)="1")
		global KeepMinion := (SubStr(settingsStr,11,1) = "1")
		global KeepNoble := (SubStr(settingsStr,12,1) = "1")
		global KeepPantry := (SubStr(settingsStr,13,1) = "1")
		global KeepRed := (SubStr(settingsStr,14,1) = "1")
		global KeepWhite := (SubStr(settingsStr,15,1) = "1")
		global TakeScreenshots := (SubStr(settingsStr,16,1) = "1")
		global WaitForDespawn := (SubStr(settingsStr,17,1) = "1")
		global DoShortWaits := (SubStr(settingsStr,18,1) = "1")
		WriteSettings()
	}
	else{
		MsgBox('Invalid input length, try again and use 14 characters',"Zoopa's Deli Macro V" Version)
		return
	}
}
;VISION TEST
^L::{
	global boxes, UIDisplay
    UIDisplay := Gui("-DPIScale +AlwaysOnTop -Caption +ToolWindow +E0x20")
    UIDisplay.BackColor := "000000"
    UIDisplay.Show("x0 y0 w" A_ScreenWidth " h" A_ScreenHeight " NA")
    WinSetTransColor "000000", UIDisplay.Hwnd
	MsgBox("Mouse over the top left of the test view and press F8","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	firstx := x
	firsty := y
	MsgBox("Mouse over the bottom right of the test view and press F8","Zoopa's Deli Macro V" Version)
	KeyWait "F8", "D"
	KeyWait "F8"
	MouseGetPos &x, &y
	secondx := x
	secondy := y
	DrawBox(UIDisplay,firstx,firsty,secondx,secondy,"Eyes")
	Loop {
		searchResult := ''
		result := 'OK'
		switch result {
			case "OK":
				searchResult := ItemSearch(firstx,firsty,secondx,secondy, true)
				if (searchResult = ''){
					result := MsgBox("I see junk. Choose OK to scan. Choose Cancel to exit.","Zoopa's Deli Macro V" Version,"OKCancel")
				}
				else{
					result := MsgBox("I see " searchResult ". Choose OK to scan. Choose Cancel to exit.","Zoopa's Deli Macro V" Version,"OKCancel")
				}
			case "Cancel":
				UIDisplay.Destroy()
				UIDisplay := ""
				return
		}
	}
}
;DELI MACRO HOTKEY
^B::{
for box in boxes{
	box.ticked := false
}
Sleep 1000
Loop{
Send "e"
Sleep 1000
Loop{
 if PixelSearch(&Px, &Py, bell.x1,bell.y1,bell.x2,bell.y2, 0xFFFFFF, 1){
	MouseMove (bell.x1+bell.x2)/2, (bell.y1+bell.y2)/2
	MouseNatural()
	Sleep 20
	Click
	MouseNatural()
	Sleep 20
	Click
	MouseNatural()
	Sleep 20
	Click
	break
 }
 else{
	Sleep 1000
	Send "e"
 }
}
Loop 30 {
	MouseMove(959, 508)
	Sleep 500
	MouseNatural()
	Click
	if (DoShortWaits){
		Send "1"
	}
	else{
		Send "2"
	}
}
Loop {
	Loop 5 {
		Sleep 1000
		Click
	}
	Sleep 500
	Send "q"
	Sleep 500
	If IsInvOpen() {
		break
	}
}
global Counter += 1
global invList
if (TakeScreenshots)
	{
	; time := FormatTime(, "HH-mm-ddd-MM-yy")
	; CaptureRegion(invList[1],invList[2],invList[3],invList[4],A_ScriptDir "\Screenshots\ZDM-C" Counter "-DT" time ".png")
	Send "{PrintScreen}"
	}
Sleep 1000
itemDropped := false
tickedCount := 0
for box in boxes{
	if (box.ticked){
		tickedCount++
		Sleep 100
		continue
	}
	if (ItemSearch(box.x1, box.y1, box.x2, box.y2)){
		box.ticked := true
		tickedCount++
		Sleep 100
		continue
	}
	else{
		DropItem((box.x1+box.x2)/2,(box.y1+box.y2)/2)
		itemDropped := true
		Sleep 250
		continue
	}
}
if (tickedCount=20){
	MsgBox()
	ExitApp
}
Sleep 500
Send "q"
Sleep 500
Loop {
	If IsInvOpen(){
		Sleep 1000
		Send "q"
	}
	else{
		break
	}
}
if(itemDropped && WaitForDespawn){
	Sleep 60000
}
} ;end of master loop
} ;end of hotkey
